apiVersion: v1
kind: Service
metadata:
  labels:
    app: golist-api
    name: golist-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  env:
    - name: DB_HOST
      value: golist-db-mariadb
    - name: DB_USER
      value: golist
    - name: DB_PASS
      value: golist
  selector:
    app: golist-api
